name: cyber_app
description: Cyber Shield

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  get_storage: ^2.1.1
  flutter_native_splash: ^2.0.4
  expandable: ^5.0.1
  syncfusion_flutter_signaturepad: ^20.4.54
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.0
  image_picker: ^0.8.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
     


  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
